### ISSUE TITLE
Adding downshift indicator for gear

### ISSUE THREAD

**Issue by zentred** [GreepTheSheep/openplanet-speedometer#5]
would be nice to be able to see a color change (of the number) when the gear is dropped

sometimes when you drop a gear, without audio, it's not so easy to notice. on certain maps if i drop a gear the only time i'll notice is when i gear back up

**Comment by GreepTheSheep** [comment]
Downshift indicator is already added in Basic and BasicDigital themes:
![image](https://github.com/GreepTheSheep/openplanet-speedometer/assets/42576124/63f4a589-b11e-409a-ac58-53e673628bc4)
